name: docs

on:
  # manual
  workflow_dispatch:
  
  # when update main branch
  push:
    branches: [main, master]

# Grant GITHUB_TOKEN the permissions required to make a Pages deployment
permissions:
  pages: write      # to deploy to Pages
  contents: write
  id-token: write   # to verify the deployment originates from an appropriate source

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        
      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
        
      # Add DevExpress source: https://docs.devexpress.com/GeneralInformation/117209/installation/install-devexpress-controls-using-nuget-packages/manage-packages-with-dotnet-cli
      - name: Add DevExpress package source
        run: dotnet nuget add source https://nuget.devexpress.com/api -n DXFeed -u DevExpress -p ${{ secrets.DEVEXPRESS_FEED_URL }}
      
      - name: Install docfx
        run: dotnet tool install -g docfx
    
      # Build docs
      - name: Run './build.cmd '
        run: ./build.cmd docs-compile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Upload docs site: https://github.com/marketplace/actions/upload-a-build-artifact
      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: docs-site
          path: docs/_site
          
      # Upload docs site: https://github.com/marketplace/actions/upload-a-build-artifact
      - name: Upload libraries
        uses: actions/upload-artifact@v4
        with:
          name: bin
          path: bin
  
  deploy:
    concurrency: ci-${{ github.ref }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      # Download Artifacts: https://github.com/actions/download-artifact
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs-site
          path: docs/_site
          
      # Publish docs: https://github.com/JamesIves/github-pages-deploy-action
      - name: Publish to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
          force: true
          branch: gh-pages
          folder: docs/_site
          git-config-name: dosymep
          git-config-email: dosymep@gmail.com